// Code generated by "stringer -type=AvailableAction"; DO NOT EDIT.

package task

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AvailableActionStart-0]
	_ = x[AvailableActionPause-1]
	_ = x[AvailableActionResume-2]
	_ = x[AvailableActionStop-3]
	_ = x[AvailableActionSwitch-4]
}

const _AvailableAction_name = "AvailableActionStartAvailableActionPauseAvailableActionResumeAvailableActionStopAvailableActionSwitch"

var _AvailableAction_index = [...]uint8{0, 20, 40, 61, 80, 101}

func (i AvailableAction) String() string {
	if i < 0 || i >= AvailableAction(len(_AvailableAction_index)-1) {
		return "AvailableAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AvailableAction_name[_AvailableAction_index[i]:_AvailableAction_index[i+1]]
}
