// Code generated by "stringer -type=PomodoroMode"; DO NOT EDIT.

package dto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PomodoroModeTask-0]
	_ = x[PomodoroModeBreaks-1]
}

const _PomodoroMode_name = "PomodoroModeTaskPomodoroModeBreaks"

var _PomodoroMode_index = [...]uint8{0, 16, 34}

func (i PomodoroMode) String() string {
	if i < 0 || i >= PomodoroMode(len(_PomodoroMode_index)-1) {
		return "PomodoroMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PomodoroMode_name[_PomodoroMode_index[i]:_PomodoroMode_index[i+1]]
}
