// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeAny-2]
	_ = x[EventTypeTaskStarted-4]
	_ = x[EventTypeTaskPaused-8]
	_ = x[EventTypeTaskResumed-16]
	_ = x[EventTypeTaskStopped-32]
	_ = x[EventTypeTaskFinished-64]
	_ = x[EventTypeBreaksStarted-128]
	_ = x[EventTypeBreaksEnded-256]
	_ = x[EventTypeTimerTicked-512]
	_ = x[EventTypeTimerFinished-1024]
}

const (
	_EventType_name_0 = "EventTypeAny"
	_EventType_name_1 = "EventTypeTaskStarted"
	_EventType_name_2 = "EventTypeTaskPaused"
	_EventType_name_3 = "EventTypeTaskResumed"
	_EventType_name_4 = "EventTypeTaskStopped"
	_EventType_name_5 = "EventTypeTaskFinished"
	_EventType_name_6 = "EventTypeBreaksStarted"
	_EventType_name_7 = "EventTypeBreaksEnded"
	_EventType_name_8 = "EventTypeTimerTicked"
	_EventType_name_9 = "EventTypeTimerFinished"
)

func (i EventType) String() string {
	switch {
	case i == 2:
		return _EventType_name_0
	case i == 4:
		return _EventType_name_1
	case i == 8:
		return _EventType_name_2
	case i == 16:
		return _EventType_name_3
	case i == 32:
		return _EventType_name_4
	case i == 64:
		return _EventType_name_5
	case i == 128:
		return _EventType_name_6
	case i == 256:
		return _EventType_name_7
	case i == 512:
		return _EventType_name_8
	case i == 1024:
		return _EventType_name_9
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
