// Code generated by "stringer -type=TimerMode"; DO NOT EDIT.

package timer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimerModeTask-0]
	_ = x[TimerModeBreaks-1]
}

const _TimerMode_name = "TimerModeTaskTimerModeBreaks"

var _TimerMode_index = [...]uint8{0, 13, 28}

func (i TimerMode) String() string {
	if i >= TimerMode(len(_TimerMode_index)-1) {
		return "TimerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimerMode_name[_TimerMode_index[i]:_TimerMode_index[i+1]]
}
